version: "2.6.1"

networks:
  local:
    driver: bridge

services: 
  postgres:
    image: postgres:13
    container_name: ecommerce_postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_postgres
    volumes:
      - pgdata:/data/postgres
    networks:
      - local
      
volumes:
  pgdata:
    driver: local